# Dependabot version updates for packages used by perfmon tooling.

version: 2
updates:
  # Enable version updates for Python packages.
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1

  # Enable version updates from GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
