name: Check Markdown links

on:
  schedule:
    # Tuesdays at 9AM PST. GitHub Actions run in UTC.
    - cron: '0 16 * * 2'

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    # Only run link checks in the main repo and not forks. The intent
    # is a low volume reminder to update stale links.
    if: github.repository == 'intel/perfmon'
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # 1.0.15
      with:
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
