# This workflow will setup Python, run create_perf_json.py, and archive
# perf JSON files.

name: Create perf json

on:
  push:
  pull_request:
  schedule:
    # Tuesdays at 9AM PST
    - cron: '0 16 * * 2'

permissions:
  contents: read

jobs:
  create-perf-json:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout perfmon
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up Python 3.x
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: "3.x"

    - name: Run unittests
      working-directory: ./scripts/unittesting
      run: python -m unittest metric_test.py test_create_perf_json.py

    - name: Create perf json files
      working-directory: ./scripts
      run: python create_perf_json.py -v

    - name: Archive perf json files
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: perf-json
        path: scripts/perf
        retention-days: 10
        if-no-files-found: error
